'use strict';
(()=>{
const $=id=>document.getElementById(id),TAU=Math.PI*2,W=1024,H=512,KEY='planet-studio-v1';
const defaults=()=>({version:1,name:'',type:'rock',color:'#8d9bf3',brush:12,opacity:85,soft:65,rough:10,bump:25,scale:35,shine:20,emission:0,atmosphere:true,airColor:'#8f9cff',airBrightness:45,airWidth:25,ring:false,ringColor:'#d6bb91',ringDistance:25,ringWidth:35,ringTilt:30,ringOpacity:90,ringPattern:1,auto:false,speed:20,tilt:15,sunAngle:-40,sunHeight:30,sunBrightness:100,stars:true,moons:[],viewX:0,viewY:0,zoom:1,phase:0});
let s=defaults(),pixels=new Uint8Array(W*H*4),undo=[],tab='paint',tool='brush',moonIndex=0,dirty=false,saveTimer,toastTimer,painting=false,pinch=false,lastPoint=null,lastStamp=null;
const palettes={rock:['#ebe6d7','#b7afa1','#756757','#3c3548','#ae644f','#dcaa6c','#688d7b','#668bbb','#8d9bf3'],gas:['#fff0d3','#e4c69c','#c9956f','#a96854','#d6a2c1','#8d78b5','#91c7d6','#4f8daf','#315574']};
function fillPixels(color){let c=hex(color);for(let i=0;i<pixels.length;i+=4){pixels[i]=c[0];pixels[i+1]=c[1];pixels[i+2]=c[2];pixels[i+3]=255;}}
function hex(c){return [parseInt(c.slice(1,3),16),parseInt(c.slice(3,5),16),parseInt(c.slice(5,7),16)];}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2500);}
function changed(){dirty=true;$('saveStatus').textContent='변경 내용 기억 중…';clearTimeout(saveTimer);saveTimer=setTimeout(save,700);}
function snapshot(){undo.push({s:structuredClone(s),pixels:pixels.slice()});if(undo.length>6)undo.shift();updateUndo();}
function updateUndo(){$('undo').disabled=!undo.length;$('undo').textContent=`↶ 되돌리기${undo.length?' ('+undo.length+')':''}`;}
function revert(){if(!undo.length)return;let a=undo.pop();s=a.s;pixels=a.pixels;upload();updateRing();background();$('planetName').value=s.name;renderPanel();updateUndo();changed();toast('한 단계 되돌렸어요');}
const canvas=$('gl'),gl=canvas.getContext('webgl',{alpha:true,antialias:true,preserveDrawingBuffer:true});
if(!gl){$('error').hidden=false;$('error').textContent='3D 화면을 실행할 수 없어요. Chrome 또는 Edge에서 하드웨어 가속을 켜고 다시 열어 주세요.';return;}
const VS=`attribute vec3 aPos;attribute vec3 aNorm;attribute vec2 aUV;uniform mat4 uModel;uniform mat4 uVP;varying vec3 vNormal;varying vec3 vWorld;varying vec2 vUV;void main(){vec4 p=uModel*vec4(aPos,1.);vWorld=p.xyz;vNormal=mat3(uModel)*aNorm;vUV=aUV;gl_Position=uVP*p;}`;
const FS=`precision mediump float;varying vec3 vNormal;varying vec3 vWorld;varying vec2 vUV;uniform sampler2D uTex;uniform vec3 uColor;uniform vec3 uLight;uniform float uBrightness;uniform float uMode;uniform float uBump;uniform float uScale;uniform float uShine;uniform float uEmission;uniform float uAlpha;uniform float uPattern;
void main(){vec3 n=normalize(vNormal);vec3 color=uColor;float alpha=uAlpha;if(uMode<.5){color=texture2D(uTex,vUV).rgb;float k=uScale;vec3 p=normalize(vWorld);vec3 wave=vec3(sin(p.y*k+sin(p.z*k*.7)),sin(p.z*k+sin(p.x*k*.7)),sin(p.x*k+sin(p.y*k*.7)));n=normalize(n+wave*uBump*.25);}else if(uMode>1.5&&uMode<2.5){float r=vUV.y;float bands=.84+.08*sin(r*150.+uPattern*1.7)+.035*sin(r*430.+uPattern*2.3);float split=.64+.035*sin(uPattern*1.8);float gap=smoothstep(.009,.021,abs(r-split));float fineGap=mix(.78,1.,smoothstep(.003,.009,abs(r-(.27+.025*cos(uPattern)))));float edge=smoothstep(0.,.018,r)*(1.-smoothstep(.98,1.,r));alpha*=gap*fineGap*edge;float lit=.36+.64*abs(dot(n,normalize(uLight)))*uBrightness;float b=dot(vWorld,normalize(uLight));float disc=b*b-dot(vWorld,vWorld)+1.;float shadow=1.;if(b<0.&&disc>0.)shadow=.32;gl_FragColor=vec4(color*bands*lit*shadow,alpha);return;}else if(uMode>2.5){vec3 eye=normalize(vec3(0.,0.,5.)-vWorld);float edge=pow(1.-abs(dot(n,eye)),2.8);gl_FragColor=vec4(color,edge*uAlpha);return;}
float d=max(dot(n,normalize(uLight)),0.);float lighting=.055+d*uBrightness;vec3 eye=normalize(vec3(0.,0.,5.)-vWorld);vec3 h=normalize(normalize(uLight)+eye);float spec=pow(max(dot(n,h),0.),16.+uShine*100.)*uShine*.55*step(.01,d);gl_FragColor=vec4(color*(lighting+uEmission)+vec3(spec),alpha);}`;
function shader(kind,src){let sh=gl.createShader(kind);gl.shaderSource(sh,src);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(sh));return sh;}
const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,VS));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,FS));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);
const uniforms={};['uModel','uVP','uTex','uColor','uLight','uBrightness','uMode','uBump','uScale','uShine','uEmission','uAlpha','uPattern'].forEach(n=>uniforms[n]=gl.getUniformLocation(program,n));
const texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);
function upload(){gl.bindTexture(gl.TEXTURE_2D,texture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,W,H,0,gl.RGBA,gl.UNSIGNED_BYTE,pixels);}
function mesh(data,indices){let b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.STATIC_DRAW);let ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(indices),gl.STATIC_DRAW);return {b,ib,count:indices.length};}
function sphere(){let d=[],ix=[],nx=96,ny=48;for(let j=0;j<=ny;j++){let v=j/ny,lat=(v-.5)*Math.PI;for(let i=0;i<=nx;i++){let u=i/nx,lon=u*TAU,x=Math.cos(lat)*Math.cos(lon),y=Math.sin(lat),z=Math.cos(lat)*Math.sin(lon);d.push(x,y,z,x,y,z,u,v);}}for(let j=0;j<ny;j++)for(let i=0;i<nx;i++){let a=j*(nx+1)+i,b=a+nx+1;ix.push(a,b,a+1,b,b+1,a+1);}return mesh(d,ix);}
function annulus(){let d=[],ix=[],n=240;for(let i=0;i<=n;i++){let a=i/n*TAU;for(let j=0;j<2;j++){let r=j?2:1;d.push(Math.cos(a)*r,0,Math.sin(a)*r,0,1,0,i/n,j);}}for(let i=0;i<n;i++){let a=i*2;ix.push(a,a+1,a+2,a+1,a+3,a+2);}return mesh(d,ix);}
const ball=sphere();let ringMesh;
function updateRing(){if(ringMesh){gl.deleteBuffer(ringMesh.b);gl.deleteBuffer(ringMesh.ib);}let d=[],ix=[],n=240,inner=1.12+s.ringDistance/100,outer=inner+.12+s.ringWidth/100;for(let i=0;i<=n;i++){let a=i/n*TAU;for(let j=0;j<2;j++){let r=j?outer:inner;d.push(Math.cos(a)*r,0,Math.sin(a)*r,0,1,0,i/n,j);}}for(let i=0;i<n;i++){let a=i*2;ix.push(a,a+1,a+2,a+1,a+3,a+2);}ringMesh=mesh(d,ix);}
const I=()=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);
function mul(a,b){let o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o;}
function rx(a){let m=I(),c=Math.cos(a),q=Math.sin(a);m[5]=c;m[6]=q;m[9]=-q;m[10]=c;return m;}
function ry(a){let m=I(),c=Math.cos(a),q=Math.sin(a);m[0]=c;m[2]=-q;m[8]=q;m[10]=c;return m;}
function rz(a){let m=I(),c=Math.cos(a),q=Math.sin(a);m[0]=c;m[1]=q;m[4]=-q;m[5]=c;return m;}
function trans(x,y,z,r=1){let m=I();m[0]=m[5]=m[10]=r;m[12]=x;m[13]=y;m[14]=z;return m;}
function vec(m,v){return [m[0]*v[0]+m[4]*v[1]+m[8]*v[2],m[1]*v[0]+m[5]*v[1]+m[9]*v[2],m[2]*v[0]+m[6]*v[1]+m[10]*v[2]];}
function inverseRotate(m,v){return [m[0]*v[0]+m[1]*v[1]+m[2]*v[2],m[4]*v[0]+m[5]*v[1]+m[6]*v[2],m[8]*v[0]+m[9]*v[1]+m[10]*v[2]];}
let aspect=1,fov=Math.PI/4,distance=5,base=I(),planetMatrix=I();
function projection(){let f=1/Math.tan(fov/2),n=.1,far=100,p=new Float32Array(16);p[0]=f/aspect;p[5]=f;p[10]=(far+n)/(n-far);p[11]=-1;p[14]=2*far*n/(n-far);return mul(p,trans(0,0,-distance));}
function draw(m,model,mode,color,alpha=1){gl.bindBuffer(gl.ARRAY_BUFFER,m.b);[['aPos',3,0],['aNorm',3,12],['aUV',2,24]].forEach(([name,size,offset])=>{let a=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,size,gl.FLOAT,false,32,offset);});gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,m.ib);gl.uniformMatrix4fv(uniforms.uModel,false,model);gl.uniform1f(uniforms.uMode,mode);gl.uniform3fv(uniforms.uColor,hex(color).map(v=>v/255));gl.uniform1f(uniforms.uAlpha,alpha);gl.drawElements(gl.TRIANGLES,m.count,gl.UNSIGNED_SHORT,0);}
function render(){gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);distance=5/s.zoom;base=mul(rx(s.viewX),ry(s.viewY));let tilted=mul(base,rz(s.tilt*Math.PI/180));planetMatrix=mul(tilted,ry(s.phase));gl.uniformMatrix4fv(uniforms.uVP,false,projection());let a=s.sunAngle*Math.PI/180,h=s.sunHeight*Math.PI/180;gl.uniform3fv(uniforms.uLight,[Math.sin(a)*Math.cos(h),Math.sin(h),Math.cos(a)*Math.cos(h)]);gl.uniform1f(uniforms.uBrightness,s.sunBrightness/100);gl.uniform1f(uniforms.uBump,s.type==='rock'?s.bump/100:0);gl.uniform1f(uniforms.uScale,6+s.scale*.7);gl.uniform1f(uniforms.uShine,s.type==='rock'?s.shine/100:.08);gl.uniform1f(uniforms.uEmission,s.type==='gas'?s.emission/100:0);gl.uniform1f(uniforms.uPattern,s.ringPattern);draw(ball,planetMatrix,0,'#ffffff');gl.uniform1f(uniforms.uBump,0);gl.uniform1f(uniforms.uEmission,0);
for(let i=0;i<s.moons.length;i++){let m=s.moons[i],angle=m.phase,r=1.45+m.distance/50,p=[Math.cos(angle)*r,0,Math.sin(angle)*r];p=vec(mul(base,rz(m.inclination*Math.PI/180)),p);draw(ball,trans(...p,m.size/100),1,m.color);}
if(s.ring){gl.depthMask(false);draw(ringMesh,mul(tilted,rx(s.ringTilt*Math.PI/180)),2,s.ringColor,s.ringOpacity/100);gl.depthMask(true);}
if(s.atmosphere){gl.depthMask(false);draw(ball,mul(planetMatrix,trans(0,0,0,1.015+s.airWidth/350)),3,s.airColor,s.airBrightness/100);gl.depthMask(true);}}
// Space is painted procedurally; no external assets or network dependency.
let seed=721;function random(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
function background(){let c=$('space'),ctx=c.getContext('2d'),w=c.width,h=c.height;seed=721;ctx.fillStyle='#030611';ctx.fillRect(0,0,w,h);for(let i=0;i<15;i++){let x=random()*w,y=random()*h,r=(.13+random()*.35)*Math.max(w,h),g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,i%2?'rgba(63,38,119,.14)':'rgba(24,69,109,.15)');g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);}if(s.stars)for(let i=0;i<Math.round(w*h/2600);i++){let x=random()*w,y=random()*h,r=.3+random()*1.1;ctx.globalAlpha=.25+random()*.7;ctx.fillStyle=i%5?'#dce6ff':'#f7dcba';ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.fill();if(r>1.25){ctx.fillRect(x-3,y-.3,6,.6);ctx.fillRect(x-.3,y-3,.6,6);}}ctx.globalAlpha=1;}
function resize(){let rect=$('stage').getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,1.7);canvas.width=Math.max(1,Math.round(rect.width*dpr));canvas.height=Math.max(1,Math.round(rect.height*dpr));$('space').width=canvas.width;$('space').height=canvas.height;aspect=rect.width/rect.height;background();}
new ResizeObserver(resize).observe($('stage'));
// Ray/sphere intersection converted into local surface coordinates.
function hit(x,y){let r=canvas.getBoundingClientRect(),dx=(2*(x-r.left)/r.width-1)*aspect*Math.tan(fov/2),dy=(1-2*(y-r.top)/r.height)*Math.tan(fov/2),len=Math.hypot(dx,dy,1),dir=[dx/len,dy/len,-1/len],b=distance*dir[2],disc=b*b-distance*distance+1;if(disc<0)return null;let t=-b-Math.sqrt(disc);if(t<0)return null;return inverseRotate(planetMatrix,[dir[0]*t,dir[1]*t,distance+dir[2]*t]);}
function uv(v){return [(Math.atan2(v[2],v[0])/TAU+1)%1,Math.asin(Math.max(-1,Math.min(1,v[1])))/Math.PI+.5];}
function pick(v){let [u,y]=uv(v),i=(Math.min(H-1,Math.floor(y*H))*W+Math.floor(u*W))*4;s.color='#'+Array.from(pixels.slice(i,i+3)).map(n=>n.toString(16).padStart(2,'0')).join('');tool='brush';renderPanel();changed();toast('표면의 색을 가져왔어요');}
// Angular brush stamps avoid UV seam breaks and keep polar strokes round.
function stamp(v){let radius=(s.brush/180)*Math.PI/2,col=hex(s.color),center=uv(v),lat=Math.asin(v[1]),gas=s.type==='gas',vertical=radius*(gas?.55:1),y0=Math.max(0,Math.floor((lat-vertical)/Math.PI*H+H/2)),y1=Math.min(H-1,Math.ceil((lat+vertical)/Math.PI*H+H/2));let source=tool==='smudge'?pixels.slice():null;
for(let y=y0;y<=y1;y++){let phi=((y+.5)/H-.5)*Math.PI,cp=Math.cos(phi),sp=Math.sin(phi),ratio=(Math.cos(radius)-sp*v[1])/(Math.max(1e-8,cp*Math.hypot(v[0],v[2]))),half=gas?Math.min(.5,radius*4/TAU/Math.max(.18,cp)):ratio<=-1?.5:ratio>=1?0:Math.acos(ratio)/TAU;if(!half)continue;let start=Math.floor((center[0]-half)*W),end=Math.ceil((center[0]+half)*W);for(let xx=start;xx<=end;xx++){let x=(xx%W+W)%W,lambda=(x+.5)/W*TAU,dot=cp*Math.cos(lambda)*v[0]+sp*v[1]+cp*Math.sin(lambda)*v[2],angle=Math.acos(Math.max(-1,Math.min(1,dot))),du=Math.min(Math.abs((x+.5)/W-center[0]),1-Math.abs((x+.5)/W-center[0])),q=gas?Math.hypot(du/Math.max(half,1e-6),(phi-lat)/vertical):angle/radius;if(q>1)continue;let edge=s.soft/100,weight=edge?Math.min(1,(1-q)/edge):1,grain=1-(s.rough/100)*random(),a=s.opacity/100*weight*grain,i=(y*W+x)*4;
for(let k=0;k<3;k++){let target=col[k];if(source){let reach=12,acc=0;for(let j=-reach;j<=reach;j++)acc+=source[(y*W+(x+j+W)%W)*4+k];target=acc/(reach*2+1);}pixels[i+k]=Math.round(pixels[i+k]*(1-a)+target*a);}}}upload();}
function stroke(v){if(lastStamp){let dot=lastStamp.reduce((sum,n,i)=>sum+n*v[i],0),angle=Math.acos(Math.max(-1,Math.min(1,dot))),steps=Math.min(80,Math.max(1,Math.ceil(angle/(s.brush*Math.PI/360*.22))));for(let j=1;j<=steps;j++){let t=j/steps,p=lastStamp.map((n,i)=>n*(1-t)+v[i]*t),l=Math.hypot(...p);stamp(p.map(n=>n/l));}}else stamp(v);lastStamp=v;}
const pointers=new Map();let gesture='none',pinchDistance=0;
canvas.addEventListener('pointerdown',e=>{e.preventDefault();canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size>=2){if(gesture==='paint'&&undo.length){pixels=undo.pop().pixels;upload();updateUndo();}gesture='pinch';painting=false;lastStamp=null;pinch=true;pinchDistance=pointerDistance();return;}let v=hit(e.clientX,e.clientY);if(v&&tool==='eyedrop'){pick(v);gesture='none';return;}if(v){snapshot();gesture='paint';painting=true;lastStamp=null;stroke(v);}else gesture='rotate';lastPoint=[e.clientX,e.clientY];});
function pointerDistance(){let p=[...pointers.values()];return p.length>=2?Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y):0;}
canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;e.preventDefault();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size>=2){let d=pointerDistance();if(pinchDistance)s.zoom=Math.max(.55,Math.min(2.5,s.zoom*d/pinchDistance));pinchDistance=d;changed();return;}if(pinch)return;if(gesture==='paint'){let v=hit(e.clientX,e.clientY);if(v)stroke(v);else lastStamp=null;}else if(gesture==='rotate'&&lastPoint){s.viewY+=(e.clientX-lastPoint[0])*.009;s.viewX=Math.max(-1.5,Math.min(1.5,s.viewX+(e.clientY-lastPoint[1])*.009));}lastPoint=[e.clientX,e.clientY];});
function endPointer(e){pointers.delete(e.pointerId);if(!pointers.size){painting=false;pinch=false;gesture='none';lastStamp=null;lastPoint=null;changed();}else if(pointers.size<2){gesture='none';painting=false;}}
canvas.addEventListener('pointerup',endPointer);canvas.addEventListener('pointercancel',endPointer);canvas.addEventListener('lostpointercapture',e=>{if(pointers.has(e.pointerId))endPointer(e);});canvas.addEventListener('wheel',e=>{e.preventDefault();s.zoom=Math.max(.55,Math.min(2.5,s.zoom*Math.exp(-e.deltaY*.001)));changed();},{passive:false});
const tabList=[['paint','✎ 붓'],['surface','◉ 표면'],['air','✧ 대기'],['ring','◎ 고리'],['moon','☾ 위성'],['motion','☀ 빛·회전']];
function title(text,note){let h=document.createElement('h2');h.textContent=text;$('panel').append(h);if(note){let p=document.createElement('p');p.className='note';p.textContent=note;$('panel').append(p);}}
function range(key,label,min,max,unit='',obj=s){let wrap=document.createElement('label');wrap.className='control';let top=document.createElement('span'),name=document.createElement('span'),out=document.createElement('output'),input=document.createElement('input');name.textContent=label;out.textContent=obj[key]+unit;top.append(name,out);input.type='range';input.min=min;input.max=max;input.value=obj[key];input.setAttribute('aria-label',label);let captured=false;input.addEventListener('pointerdown',()=>{snapshot();captured=true;},{passive:true});input.addEventListener('input',()=>{if(!captured){snapshot();captured=true;}obj[key]=Number(input.value);out.textContent=obj[key]+unit;if(key.startsWith('ring'))updateRing();changed();});input.addEventListener('change',()=>captured=false);wrap.append(top,input);$('panel').append(wrap);}
function color(key,label,obj=s){let l=document.createElement('label');l.className='control';let sp=document.createElement('span');sp.textContent=label;let i=document.createElement('input');i.type='color';i.value=obj[key];i.setAttribute('aria-label',label);i.addEventListener('change',()=>{snapshot();obj[key]=i.value;changed();if(key==='color')renderPanel();});l.append(sp,i);$('panel').append(l);}
function check(key,label){let l=document.createElement('label');l.className='check';let t=document.createElement('span');t.textContent=label;let i=document.createElement('input');i.type='checkbox';i.checked=s[key];i.addEventListener('change',()=>{snapshot();s[key]=i.checked;if(key==='stars')background();renderPanel();changed();});l.append(t,i);$('panel').append(l);}
function buttons(items){let row=document.createElement('div');row.className='row';items.forEach(([label,fn,active])=>{let b=document.createElement('button');b.textContent=label;if(active)b.className='selected';b.onclick=fn;row.append(b);});$('panel').append(row);}
function toggleAuto(){snapshot();s.auto=!s.auto;renderPanel();changed();}
function renderPanel(){let tabs=$('tabs');tabs.replaceChildren();tabList.forEach(([key,label])=>{let b=document.createElement('button');b.textContent=label;b.className=tab===key?'active':'';b.setAttribute('aria-pressed',String(tab===key));b.onclick=()=>{tab=key;renderPanel();};tabs.append(b);});$('panel').replaceChildren();$('pause').textContent=s.auto?'Ⅱ 모두 멈추기':'▶ 저절로 돌기';
if(tab==='paint'){title('색으로 빚는 나의 행성','행성 위를 누르고 움직여 색칠하세요. 바깥 빈 곳을 끌면 뒷면도 볼 수 있어요.');buttons([['✎ 색칠',()=>{tool='brush';renderPanel();},tool==='brush'],['⌾ 스포이드',()=>{tool='eyedrop';renderPanel();toast('가져올 색을 행성에서 눌러 주세요');},tool==='eyedrop']]);let sw=document.createElement('div');sw.className='swatches';palettes[s.type].forEach(c=>{let b=document.createElement('button');b.style.background=c;b.title=c;b.setAttribute('aria-label',`색 ${c}`);if(s.color.toLowerCase()===c)b.className='selected';b.onclick=()=>{s.color=c;tool='brush';renderPanel();changed();};sw.append(b);});$('panel').append(sw);color('color','내가 고른 색');range('brush','붓 크기',2,45);range('opacity','색 진하기',5,100,'%');range('soft','가장자리 부드럽게',0,100,'%');range('rough','붓 자국 거칠기',0,100,'%');if(s.type==='gas')buttons([['↔ 옆으로 문지르기',()=>{tool=tool==='smudge'?'brush':'smudge';renderPanel();},tool==='smudge']]);buttons([['행성 전체 채우기',()=>{snapshot();fillPixels(s.color);upload();changed();toast('행성 전체를 선택한 색으로 채웠어요');}],['↶ 되돌리기',revert]]);}
if(tab==='surface'){title('어떤 행성을 만들까요?','종류를 바꿔도 지금까지 칠한 색은 남아 있어요.');buttons([['암석형',()=>{snapshot();s.type='rock';tool='brush';renderPanel();changed();},s.type==='rock'],['가스형',()=>{snapshot();s.type='gas';tool='brush';renderPanel();changed();},s.type==='gas']]);if(s.type==='rock'){range('bump','표면 울퉁불퉁하게',0,100,'%');range('scale','울퉁불퉁한 무늬 촘촘함',0,100);range('shine','반짝이는 정도',0,100,'%');let p=document.createElement('p');p.className='note';p.textContent='요철은 빛과 그림자로 표현됩니다. 무늬 촘촘함을 낮추면 큰 무늬가 돼요.';$('panel').append(p);}else{let p=document.createElement('p');p.className='note';p.textContent='붓이 옆으로 길게 펼쳐져 띠를 만들어요. 붓 탭에서 ‘옆으로 문지르기’를 선택하면 색을 가로로 섞을 수 있어요.';$('panel').append(p);range('emission','상상 속 은은한 빛',0,70,'%');let n=document.createElement('p');n.className='warning';n.textContent='상상 표현이에요. 실제 행성을 관찰할 때 보이는 빛은 주로 태양빛을 반사한 것입니다.';$('panel').append(n);}}
if(tab==='air'){title('행성을 감싸는 빛','가장자리에 은은한 대기 빛을 둘러 보세요.');check('atmosphere','대기 빛 켜기');if(s.atmosphere){color('airColor','빛 색');range('airBrightness','밝기',0,100,'%');range('airWidth','퍼지는 넓이',0,100);}}
if(tab==='ring'){title('토성처럼 펼쳐지는 고리','넓은 띠와 동심원 무늬를 만들어요. 기울기 25~40°에서 고리 면이 잘 보여요.');check('ring','고리 넣기');if(s.ring){buttons([['토성 고리 모양으로',()=>{snapshot();s.ringColor='#d6bb91';s.ringDistance=25;s.ringWidth=60;s.ringTilt=30;s.ringOpacity=90;s.ringPattern=1;updateRing();renderPanel();changed();}]]);color('ringColor','고리 색');range('ringDistance','행성에서 떨어진 거리',0,100);range('ringWidth','고리 넓이',1,100);range('ringTilt','고리 기울기',-80,80,'°');range('ringOpacity','고리 진하기',5,100,'%');range('ringPattern','고리 사이 틈 무늬',1,8);}}
if(tab==='moon'){title('함께 도는 작은 위성',`최대 8개 · 지금 ${s.moons.length}개`);buttons([['＋ 위성 넣기',()=>{if(s.moons.length>=8){toast('위성은 최대 8개까지 넣을 수 있어요');return;}snapshot();s.moons.push({color:['#cfc6b8','#c6b1a4','#8ca6b9','#c5accc'][s.moons.length%4],size:12,distance:25+s.moons.length*12,speed:20,inclination:s.moons.length*12-20,phase:s.moons.length*2.4});moonIndex=s.moons.length-1;renderPanel();changed();}],['선택 위성 빼기',()=>{if(!s.moons.length)return;snapshot();s.moons.splice(moonIndex,1);moonIndex=Math.max(0,moonIndex-1);renderPanel();changed();}]]);if(s.moons.length){moonIndex=Math.min(moonIndex,s.moons.length-1);let row=document.createElement('div');row.className='moon-tabs';s.moons.forEach((m,i)=>{let b=document.createElement('button');b.textContent=i+1;b.setAttribute('aria-label',`위성 ${i+1} 선택`);if(i===moonIndex)b.className='selected';b.onclick=()=>{moonIndex=i;renderPanel();};row.append(b);});$('panel').append(row);let m=s.moons[moonIndex];color('color',`위성 ${moonIndex+1} 색`,m);range('size','크기',5,30,'',m);range('distance','행성에서 떨어진 거리',0,150,'',m);range('speed','도는 속도',0,100,'',m);range('inclination','도는 길 기울기',-85,85,'°',m);}else{let p=document.createElement('p');p.className='note';p.textContent='위성을 넣고 빛·회전 탭에서 저절로 돌기를 켜 보세요.';$('panel').append(p);}}
if(tab==='motion'){title('빛과 움직임','모두 멈추면 행성과 위성이 함께 멈춰요. 바깥 드래그로는 계속 돌려 볼 수 있어요.');buttons([[s.auto?'Ⅱ 모두 멈추기':'▶ 저절로 돌기',toggleAuto,s.auto]]);range('speed','행성 도는 속도',0,100);range('tilt','행성 기울기',-90,90,'°');let d=document.createElement('div');d.className='divider';$('panel').append(d);range('sunAngle','햇빛 좌우 방향',-180,180,'°');range('sunHeight','햇빛 위아래 방향',-80,80,'°');range('sunBrightness','햇빛 밝기',0,160,'%');check('stars','배경 별 보이기');}}
function pixelsURL(){let c=document.createElement('canvas');c.width=W;c.height=H;let cx=c.getContext('2d');cx.putImageData(new ImageData(new Uint8ClampedArray(pixels),W,H),0,0);return c.toDataURL('image/png');}
function project(){return {format:'planet-studio',version:1,state:s,texture:pixelsURL()};}
let db;
let recording=null;
function openDB(){return new Promise((resolve,reject)=>{let req=indexedDB.open(KEY,1);req.onupgradeneeded=()=>req.result.createObjectStore('work');req.onsuccess=()=>{db=req.result;resolve(db);};req.onerror=()=>reject(req.error);});}
async function save(){if(recording)return;if(!db){$('saveStatus').textContent='자동 기억 불가 · 작업 저장을 이용하세요';return;}try{const data=project();await new Promise((resolve,reject)=>{let tx=db.transaction('work','readwrite');tx.objectStore('work').put(data,'last');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});dirty=false;$('saveStatus').textContent='✓ 이 기기에 자동 기억했어요';}catch(e){$('saveStatus').textContent='자동 기억 실패 · 작업 저장을 이용하세요';}}
const bounds={brush:[2,45],opacity:[5,100],soft:[0,100],rough:[0,100],bump:[0,100],scale:[0,100],shine:[0,100],emission:[0,70],airBrightness:[0,100],airWidth:[0,100],ringDistance:[0,100],ringWidth:[1,100],ringTilt:[-80,80],ringOpacity:[5,100],ringPattern:[1,8],speed:[0,100],tilt:[-90,90],sunAngle:[-180,180],sunHeight:[-80,80],sunBrightness:[0,160],viewX:[-1.5,1.5],viewY:[-10000,10000],zoom:[.55,2.5],phase:[-100000,100000]};
function validate(data){if(!data||data.format!=='planet-studio'||data.version!==1||!data.state||typeof data.texture!=='string'||!/^data:image\/png;base64,/.test(data.texture)||data.texture.length>6e6)throw Error('올바른 행성 작업 파일이 아니에요');let src=data.state,out=defaults();for(let [key,[lo,hi]]of Object.entries(bounds)){let n=src[key];if(typeof n==='number'&&Number.isFinite(n))out[key]=Math.max(lo,Math.min(hi,n));}for(let k of ['color','airColor','ringColor'])if(/^#[0-9a-f]{6}$/i.test(src[k]))out[k]=src[k];for(let k of ['auto','atmosphere','ring','stars'])if(typeof src[k]==='boolean')out[k]=src[k];out.type=src.type==='gas'?'gas':'rock';out.name=typeof src.name==='string'?src.name.slice(0,30):'';if(Array.isArray(src.moons))out.moons=src.moons.slice(0,8).map((m,i)=>({color:/^#[0-9a-f]{6}$/i.test(m?.color)?m.color:'#cfc6b8',size:limit(m?.size,5,30,12),distance:limit(m?.distance,0,150,30),speed:limit(m?.speed,0,100,20),inclination:limit(m?.inclination,-85,85,0),phase:limit(m?.phase,-100000,100000,i)}));return out;}
function limit(n,a,b,f){return typeof n==='number'&&Number.isFinite(n)?Math.max(a,Math.min(b,n)):f;}
async function restore(data){let next=validate(data);let image=await new Promise((resolve,reject)=>{let im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(Error('색칠 데이터를 읽을 수 없어요'));im.src=data.texture;});if(image.width!==W||image.height!==H)throw Error('색칠 데이터의 크기가 맞지 않아요');let c=document.createElement('canvas');c.width=W;c.height=H;let cx=c.getContext('2d');cx.drawImage(image,0,0);let nextPixels=new Uint8Array(cx.getImageData(0,0,W,H).data);s=next;pixels=nextPixels;upload();updateRing();background();$('planetName').value=s.name;tool='brush';renderPanel();}
function download(blob,filename){let u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(u),10000);}
function safeName(){return (s.name||'나만의_행성').replace(/[\\/:*?"<>|]/g,'_');}
$('export').onclick=()=>download(new Blob([JSON.stringify(project())],{type:'application/json'}),safeName()+'.planet.json');$('import').onclick=()=>$('file').click();$('file').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{if(f.size>7e6)throw Error('작업 파일이 너무 커요');let data=JSON.parse(await f.text());validate(data);snapshot();await restore(data);changed();toast('행성 작업을 불러왔어요');}catch(err){toast(err.message||'파일을 읽을 수 없어요');}e.target.value='';};
$('png').onclick=()=>{try{render();let c=document.createElement('canvas');c.width=1600;c.height=1000;let ctx=c.getContext('2d');ctx.fillStyle='#040713';ctx.fillRect(0,0,1600,1000);let scale=Math.min(1600/canvas.width,900/canvas.height),w=canvas.width*scale,h=canvas.height*scale,x=(1600-w)/2,y=(900-h)/2;ctx.drawImage($('space'),x,y,w,h);ctx.drawImage(canvas,x,y,w,h);ctx.fillStyle='#eff0ff';ctx.font='600 30px system-ui';ctx.textAlign='center';ctx.fillText(s.name||'나만의 행성',800,946);ctx.fillStyle='#a2abc6';ctx.font='15px system-ui';ctx.fillText('나만의 행성 공방',800,977);c.toBlob(b=>{if(b){download(b,safeName()+'.png');toast('완성작 PNG를 저장했어요');}else toast('PNG 저장에 실패했어요');},'image/png');}catch(e){toast('PNG 저장에 실패했어요');}};
$('reset').onclick=()=>{if(!confirm('새 행성을 만들까요? 지금 작품은 작업 저장으로 보관할 수 있어요.'))return;snapshot();s=defaults();fillPixels(s.color);upload();updateRing();background();$('planetName').value='';tool='brush';renderPanel();changed();};
$('undo').onclick=revert;$('pause').onclick=toggleAuto;$('menu').onclick=()=>document.body.classList.toggle('tools-open');$('home').onclick=()=>{s.viewX=s.viewY=0;s.zoom=1;changed();};$('zoomIn').onclick=()=>{s.zoom=Math.min(2.5,s.zoom*1.15);changed();};$('zoomOut').onclick=()=>{s.zoom=Math.max(.55,s.zoom/1.15);changed();};$('planetName').oninput=e=>{s.name=e.target.value;changed();};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&!['INPUT','TEXTAREA'].includes(e.target.tagName)){e.preventDefault();revert();}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&recording){recording.cancelled=true;recording.reason='창을 이동해서 저장을 중단했어요. 다시 시도해 주세요';}if(document.hidden&&dirty)save();});window.addEventListener('pagehide',()=>{if(dirty)save();});
function captureCanvas(w,h){let c=document.createElement('canvas');c.width=w;c.height=h;return c;}
function composeCapture(c){let ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.fillStyle='#040713';ctx.fillRect(0,0,w,h);let sceneH=h*.90,scale=Math.min(w/canvas.width,sceneH/canvas.height),cw=canvas.width*scale,ch=canvas.height*scale,x=(w-cw)/2,y=(sceneH-ch)/2;ctx.drawImage($('space'),x,y,cw,ch);ctx.drawImage(canvas,x,y,cw,ch);ctx.fillStyle='#eff0ff';ctx.textAlign='center';ctx.font=`600 ${Math.round(h*.035)}px system-ui`;ctx.fillText(s.name||'나만의 행성',w/2,h*.955);}
function rotationAt(job,t){s.phase=job.phase+TAU*t;s.moons.forEach((m,i)=>{m.phase=job.moons[i]+TAU*t*(m.speed/Math.max(1,s.speed));});render();}
function beginRecording(kind){if(recording)return null;clearTimeout(saveTimer);let job={kind,phase:s.phase,moons:s.moons.map(m=>m.phase),cancelled:false,reason:'저장을 취소했어요',disabled:[],worker:null,recorder:null,stream:null,rejectEncode:null};recording=job;document.querySelectorAll('button,input').forEach(el=>{if(el.id==='cancelRecording')return;job.disabled.push([el,el.disabled]);el.disabled=true;});$('recording').hidden=false;$('recordTitle').textContent=kind==='gif'?'회전 GIF 만드는 중':'회전 영상 만드는 중';$('recordInfo').textContent='6초 동안 한 바퀴 돌아요. 창을 그대로 열어 두세요.';$('recordProgress').value=0;return job;}
function finishRecording(job){job.worker?.terminate();if(job.recorder&&job.recorder.state!=='inactive'){try{job.recorder.stop();}catch(e){}}job.stream?.getTracks().forEach(t=>t.stop());s.phase=job.phase;s.moons.forEach((m,i)=>m.phase=job.moons[i]);job.disabled.forEach(([el,disabled])=>el.disabled=disabled);recording=null;$('recording').hidden=true;updateUndo();render();if(dirty)save();}
function checkRecording(job){if(job.cancelled||document.hidden)throw Error(job.reason);}
function nextPaint(){return new Promise(resolve=>requestAnimationFrame(resolve));}
$('cancelRecording').onclick=()=>{if(recording){recording.cancelled=true;recording.rejectEncode?.(Error(recording.reason));}};
async function gifRecording(){let job=beginRecording('gif');if(!job)return;try{if(typeof Worker==='undefined')throw Error('이 브라우저에서는 GIF 저장을 지원하지 않아요');let c=captureCanvas(480,300),frames=[],total=50;for(let i=0;i<total;i++){checkRecording(job);rotationAt(job,i/total);composeCapture(c);frames.push(c.getContext('2d').getImageData(0,0,c.width,c.height).data.buffer);$('recordProgress').value=Math.round((i+1)/total*55);await nextPaint();}
 $('recordTitle').textContent='GIF 파일로 변환하는 중';$('recordInfo').textContent='기기에 따라 조금 걸릴 수 있어요.';
 let result=await new Promise((resolve,reject)=>{job.rejectEncode=reject;job.worker=new Worker('gif-worker.js');job.worker.onmessage=e=>{if(e.data.error)reject(Error(e.data.error));else if(e.data.done)resolve(e.data.buffer);else $('recordProgress').value=55+Math.round(e.data.progress*.45);};job.worker.onerror=()=>reject(Error('GIF 저장에 실패했어요. GitHub Pages 주소에서 다시 시도해 주세요'));job.worker.postMessage({width:c.width,height:c.height,frames,delay:12},frames);});checkRecording(job);download(new Blob([result],{type:'image/gif'}),safeName()+'_회전.gif');toast('6초 반복 GIF를 저장했어요');}catch(e){toast(e.message||'GIF 저장에 실패했어요');}finally{finishRecording(job);}}
function videoFormat(){if(typeof MediaRecorder==='undefined')return null;return ['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm','video/mp4'].find(type=>MediaRecorder.isTypeSupported(type))||null;}
async function videoRecording(){let mime=videoFormat();if(!mime||typeof HTMLCanvasElement==='undefined'||!HTMLCanvasElement.prototype.captureStream){toast('영상 저장을 지원하지 않는 브라우저예요. GIF 저장을 이용해 주세요');return;}let job=beginRecording('video');if(!job)return;try{let c=captureCanvas(1280,800);rotationAt(job,0);composeCapture(c);job.stream=c.captureStream(30);let chunks=[],rec=job.recorder=new MediaRecorder(job.stream,{mimeType:mime,videoBitsPerSecond:4000000}),recError=null;
 let stopped=new Promise(resolve=>{rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};rec.onerror=e=>{recError=e.error||Error('영상 녹화에 실패했어요');resolve();};rec.onstop=resolve;});rec.start(250);let start=performance.now();while(true){checkRecording(job);if(recError)throw recError;let t=Math.min(1,(performance.now()-start)/6000);rotationAt(job,t);composeCapture(c);$('recordProgress').value=Math.round(t*100);if(t>=1)break;await nextPaint();}if(rec.state!=='inactive')rec.stop();await stopped;checkRecording(job);if(recError)throw recError;if(!chunks.length)throw Error('영상 데이터를 저장하지 못했어요');let ext=mime.includes('mp4')?'mp4':'webm';download(new Blob(chunks,{type:mime}),safeName()+'_회전.'+ext);toast(`6초 회전 영상(${ext.toUpperCase()})을 저장했어요`);}catch(e){toast(e.message||'영상 저장에 실패했어요');}finally{finishRecording(job);}}
$('gif').onclick=gifRecording;$('video').onclick=videoRecording;

let last=performance.now(),lastAnimationSave=last;
function frame(now){let dt=Math.min(.05,(now-last)/1000);last=now;if(!recording&&s.auto&&!painting&&!pointers.size){s.phase=(s.phase+dt*s.speed*.012)%TAU;s.moons.forEach(m=>m.phase=(m.phase+dt*m.speed*.012)%TAU);if(now-lastAnimationSave>10000){lastAnimationSave=now;save();}}render();requestAnimationFrame(frame);}
fillPixels(s.color);upload();updateRing();renderPanel();updateUndo();resize();requestAnimationFrame(frame);
(async()=>{try{await openDB();let data=await new Promise((resolve,reject)=>{let r=db.transaction('work').objectStore('work').get('last');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});if(data){await restore(data);toast('마지막 행성에서 이어서 만들어요');}$('saveStatus').textContent='✓ 이 기기에 자동 기억해요';}catch(e){$('saveStatus').textContent='자동 기억 불가 · 작업 저장을 이용하세요';}})();
})();
